name: native_push
description: "The Native Push Plugin is a Flutter plugin that provides seamless integration of push notifications across different platforms including Android, iOS, macOS, and Web. "
version: 1.0.2
repository: https://github.com/native-Push/native_push

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  web: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.opdehipt.native_push
        pluginClass: NativePushPlugin
      ios:
        pluginClass: NativePushPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: NativePushPlugin
        sharedDarwinSource: true
      web:
        pluginClass: NativePushWeb
        fileName: src/native_push_web.dart

false_secrets:
  - example/lib/main.dart